site_name: Reloading Book
site_url: https://reloading.github.io
site_author: dsgnr
site_description: My notes and documentation for F-class reloading.

# Repository
repo_name: dsgnr/reloading-book
repo_url: https://github.com/dsgnr/reloading-book

# Copyright
copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script>

extra_css:
  - static/css/custom.css

# Configuration
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - offline
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

# Additional configuration
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dsgnr

# Extensions
markdown_extensions:
  - toc:
      permalink: true
